class NBA_Team_Ranking < ActiveRecord::Base
  scope :team, lambda{|team| where("team IN (?)", team )}
  default_scope {where("(team IN (SELECT awayteam FROM nba_schedule WHERE game_date = TO_DATE(?, 'DD/MM/YYYY')) OR team IN (SELECT hometeam FROM nba_schedule WHERE game_date = TO_DATE(?, 'DD/MM/YYYY')))", NBA_Lineup.current_date, NBA_Lineup.current_date )}
  
  def self.update_ranking( rankings )
    rankings.each do |d|
      NBA_Team_Ranking.delete_all(team: d[:team])
      
            NBA_Team_Ranking.create(
                                  team: d[:team],
                                  fga_rank: d[:fga_rank],
                                  fgm_rank: d[:fgm_rank],
                                  fg_pct_rank: d[:fg_pct_rank],
                                  tpm_rank: d[:tpm_rank],
                                  tpa_rank: d[:tpa_rank],
                                  tp_pct_rank: d[:tp_pct_rank],
                                  ftm_rank: d[:ftm_rank],
                                  fta_rank: d[:fta_rank],
                                  ft_pct_rank: d[:ft_pct_rank],
                                  orb_rank: d[:orb_rank],
                                  drb_rank: d[:drb_rank],
                                  trb_rank: d[:trb_rank],
                                  assists_rank: d[:assists_rank],
                                  steals_rank: d[:steals_rank],
                                  blocks_rank: d[:blocks_rank],
                                  tov_rank: d[:tov_rank],
                                  pf_rank: d[:pf_rank],
                                  points_rank: d[:points_rank],
                                  opp_fga_rank: d[:opp_fga_rank],
                                  opp_fgm_rank: d[:opp_fgm_rank],
                                  opp_fg_pct_rank: d[:opp_fg_pct_rank],
                                  opp_tpm_rank: d[:opp_tpm_rank],
                                  opp_tpa_rank: d[:opp_tpa_rank],
                                  opp_tp_pct_rank: d[:opp_tp_pct_rank],
                                  opp_ftm_rank: d[:opp_ftm_rank],
                                  opp_fta_rank: d[:opp_fta_rank],
                                  opp_ft_pct_rank: d[:opp_ft_pct_rank],
                                  opp_orb_rank: d[:opp_orb_rank],
                                  opp_drb_rank: d[:opp_drb_rank],
                                  opp_trb_rank: d[:opp_trb_rank],
                                  opp_assists_rank: d[:opp_assists_rank],
                                  opp_steals_rank: d[:opp_steals_rank],
                                  opp_blocks_rank: d[:opp_blocks_rank],
                                  opp_tov_rank: d[:opp_tov_rank],
                                  opp_pf_rank: d[:opp_pf_rank],
                                  opp_points_rank: d[:opp_points_rank],
                                  fgm: d[:fgm],
                                  fga: d[:fga],
                                  fg_pct: d[:fg_pct],
                                  tpm: d[:tpm],
                                  tpa: d[:tpa],
                                  tp_pct: d[:tp_pct],
                                  ftm: d[:ftm],
                                  fta: d[:fta],
                                  ft_pct: d[:ft_pct],
                                  orb: d[:orb],
                                  drb: d[:drb],
                                  trb: d[:trb],
                                  assists: d[:assists],
                                  steals: d[:steals],
                                  blocks: d[:blocks],
                                  tov: d[:tov],
                                  pf: d[:pf],
                                  points: d[:points],
                                  opp_fgm: d[:opp_fgm],
                                  opp_fga: d[:opp_fga],
                                  opp_fg_pct: d[:opp_fg_pct],
                                  opp_tpm: d[:opp_tpm],
                                  opp_tpa: d[:opp_tpa],
                                  opp_tp_pct: d[:opp_tp_pct],
                                  opp_ftm: d[:opp_ftm],
                                  opp_fta: d[:opp_fta],
                                  opp_ft_pct: d[:opp_ft_pct],
                                  opp_orb: d[:opp_orb],
                                  opp_drb: d[:opp_drb],
                                  opp_trb: d[:opp_trb],
                                  opp_assists: d[:opp_assists],
                                  opp_steals: d[:opp_steals],
                                  opp_blocks: d[:opp_blocks],
                                  opp_tov: d[:opp_tov],
                                  opp_pf: d[:opp_pf],
                                  opp_points: d[:opp_points]
                           )
    end
  end
  
end
